<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageReference Include="Xunit.SkippableFact" Version="1.4.13" />
    <PackageReference Include="Xunit.StaFact" Version="1.2.69" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildOrchestrator.Contracts\BuildOrchestrator.Contracts.csproj" />
    <ProjectReference Include="..\..\src\BuildOrchestrator.Core\BuildOrchestrator.Core.csproj" />
    <ProjectReference Include="..\..\src\BuildOrchestrator.Supervisor\BuildOrchestrator.Supervisor.csproj" />
    <ProjectReference Include="..\..\src\BuildOrchestrator.App\BuildOrchestrator.App.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\src\BuildOrchestrator.App\Fonts\*.otf" Link="TestAssets\Fonts\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\src\BuildOrchestrator.App\Fonts\*.CompositeFont" Link="TestAssets\Fonts\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
